name: Publish Docker Image

on:
  push:
    branches:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Code Checkout
      - uses: docker://ghcr.io/deeepvision/github-action-docker-build/docker-build:1.1
        name: Build Docker Image
        with:
          name: traefik-proxy
          registryType: ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
